# Generated by Django 5.0.6 on 2024-08-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0004_alter_scriptexecution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptexecution",
            name="script",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="Web.script"
            ),
        ),
        migrations.CreateModel(
            name="ScriptCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=300)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Web.scriptexecution",
                    ),
                ),
            ],
        ),
    ]
