# Generated by Django 5.0.6 on 2024-08-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0005_alter_scriptexecution_script_scriptcommand"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("command", models.CharField(max_length=300)),
                ("output_log_file_path", models.CharField(max_length=255)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="Web.scriptexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
