"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import argparse
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i$3i#v$0!$g(ry(@v7b2v-bydv=h=!8#i+f%y#%#6+neyfu2te'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ORIGIN_WHITELIST = [
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3001",
    'http://0.0.0.0:3000',  # Next.js 開發伺服器
    'http://0.0.0.0:3001',  # Next.js 開發伺服器
    'http://49.213.238.75:3000',  # 確保包含協議
    'http://192.168.0.135:8000',
    'http://192.168.0.135:3000',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:3001']

CSRF_COOKIE_SAMESITE = 'None'  # 允许跨站请求伪造（CSRF）
CSRF_COOKIE_SECURE = False  # 如果没有 HTTPS，设置为 False
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = False
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
    'PATCH',
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ORIGIN_ALLOW_ALL = True
# settings.py


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # 允许来自 Next.js 的请求
]


# Application definition


INSTALLED_APPS = [
    # 'daphne',
    # 'channels',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    # 'iframe',
    "Web",
    "Box",
]


# BASE_MEDIA_DIR =  os.environ.get('BASE_MEDIA_DIR','/Users/hungwei/Documents/all')

# MEDIA_URL = '/media/'

MIDDLEWARE = [
    'Web.middleware.PublicAccessControlMiddleware',  # 添加你的自定義中間件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'iframe.middleware.IframeMiddleware',

]


ROOT_URLCONF = 'server.urls'
APPEND_SLASH=False 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'server.wsgi.application'

# ASGI_APPLICATION = 'server.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'music',
    #     'USER': 'gWvPZkyaanAP5cXQqE8hkX5hnmYYhcMr',
    #     'PASSWORD': 'ZkyaanAP5cXQqE8hkX5hnmYYhcMr',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3306',
    #     'OPTIONS': {
    #             'sql_mode': 'STRICT_ALL_TABLES',
    #     }
    # },
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'MAKERTHON',
    #     'USER': 'gWvPZkyaanAP5cXQqE8hkX5hnmYYhcMr',
    #     'PASSWORD': 'ZkyaanAP5cXQqE8hkX5hnmYYhcMr',
    #     'HOST': '49.213.238.75',
    #     'PORT': '3306',
    #     'OPTIONS': {
    #         'sql_mode': 'STRICT_ALL_TABLES',
    #     }
    # },

}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / "static",
    # BASE_DIR / "myapp/static/css",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# key
API_KEY = '4VGFO2C4IBN542V0DRAIAP7TR6UG1L'


 # 设置ASGI应用
 
 # 设置通道层的通信后台 - 本地测试用
CHANNEL_LAYERS = {
     "default": {
         "BACKEND": "channels.layers.InMemoryChannelLayer"
     }
}

MQTT_SERVER = '889b3e962de249669b98e8b986e948eb.s1.eu.hivemq.cloud'
MQTT_PORT = 8884
MQTT_KEEPALIVE = 60
MQTT_USER = 'client_iot_0515'
MQTT_PASSWORD = 'client_iot_0515A'


JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
}


#============================
#
# self middleware settings
#
#============================

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost',
#     'http://127.0.0.1',
#     'http://49.213.238.75'
# ]

# CORS_ALLOW_METHODS = [
#     'GET',
#     'POST',
#     'PUT',
#     'DELETE',
#     'OPTIONS'
# ]

# CORS_ALLOW_HEADERS = [
#     'Content-Type',
#     'Authorization'
# ]

# CORS_MAX_AGE = 86400

# ALLOWED_HOSTS_FOR_FRAMES = [
#     'localhost',
#     '127.0.0.1',
#     '49.213.238.75'
# ]
