version: "3.8"

services:
  nginx1:
    build:
      context: ./script/nginx1
      dockerfile: Dockerfile
    container_name: nginx1
    ports:
      - "8001:8001" # 映射容器的80端口到主机的8001端口
    volumes:
      - type: bind
        source: ./script/nginx1/nginx1.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /Volumes/lai/data
        target: /data
    networks:
      - nginx-network

  nginx2:
    build:
      context: ./script/nginx2
      dockerfile: Dockerfile
    container_name: nginx2
    ports:
      - "8002:8002" # 映射容器的80端口到主机的8002端口
    volumes:
      - type: bind
        source: ./script/nginx2/nginx2.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /Volumes/lai/data
        target: /data
    networks:
      - nginx-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
