import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Sidebar } from "./components/Sidebar";
import { ScrollPositionProvider } from "./components/ScrollRestorationContext";
import ScrollRestoration from "./components/ScrollRestoration";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en dark-model">
      <ScrollPositionProvider>
        {/* <ScrollRestoration> */}
        <body className={inter.className}>
          <div>
            <Navbar />
            {children}
            {/* <div className="fixed top-0 left-0 ">
            <Sidebar />
            </div> */}
          </div>
        </body>
        {/* </ScrollRestoration> */}
      </ScrollPositionProvider>
    </html>
  );
}
